# Generated by Django 4.1.12 on 2024-02-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sde', 'Software Development Engineer'), ('qa', 'Quality Assurance Engineer'), ('pm', 'Product Manager'), ('dba', 'Database Administrator'), ('se', 'Systems Engineer')], max_length=255)),
                ('topic', models.CharField(choices=[('ds', 'Data Structures'), ('algo', 'Algorithms'), ('oop', 'Object-Oriented Programming'), ('db', 'Databases'), ('web', 'Web Development'), ('os', 'Operating Systems'), ('network', 'Computer Networks')], max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], max_length=10)),
                ('question', models.TextField()),
            ],
        ),
    ]
